[workspace]
members = [
    "bth_message",
    "bth_network",
    "bitcoin_node",
]

resolver = "2"

[workspace.dependencies]
anyhow = "1.0.81"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
