[package]
name = "bth_message"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
num_enum = "0.7.2"
sha2 = "0.11.0-pre.3"
bytes = "1.0.0"
nom = "7.1.3"
anyhow = { workspace = true }
