[package]
name = "bth_network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
futures = "0.3.30"
bth_message = { path = "../bth_message" }
