[package]
name = "bth_network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
bytes = "*"
bth_message = { path = "../bth_message" }
anyhow = "1.0.86"
futures = "0.3.30"